# description: Global help for Kronos
function __kronos_help --description "Global help for Kronos"
    echo "Usage: kronos <command> [options]"
    echo ""
    echo "Active Directory attack orchestrator."
    echo ""
    echo "Commands:"
    echo "  userenum    Run kerbrute userenum (auto-saves valid_users.txt)"
    echo "  dominfo     Query domain info and password policy"
    echo "  ingest      Ingest Active Directory data using bloodhound-python"
    echo "  rdp         Connect via RDP (xfreerdp3)"
    echo "  winrm       Connect via WinRM (evil-winrm)"
    echo "  ftp         Connect via FTP"
    echo "  smb         Connect via SMB (smbclient)"
    echo "  rpc         Connect via RPC (rpcclient)"
    echo "  asrep-roast Run AS-REP Roasting using GetNPUsers.py"
    echo "  kerbroast   Run Kerberoasting using GetUserSPNs.py"
    echo "  lookupsid   Enumerate SIDs for AD objects using lookupsid.py"
    echo "  spray       Password spray using valid_users.txt via nxc"
    echo "  forcechange Force change a user's password using bloodyAD"
    echo "  gmsa        Read GMSA passwords using nxc ldap"
    echo "  ticket      Create Golden and Silver Tickets using ticketer.py"
    echo "  convert     Convert tickets between kirbi and ccache formats"
    echo "  request     Request TGT or ST and export KRB5CCNAME"
    echo "  install     Install all external dependencies"
    echo "  help        Show this global help message or command-specific help"
    echo ""
    echo "Run 'kronos <command> help' or 'kronos help <command>' for more information on a specific command."
end
