# description: Global help for Kronos
function __kronos_help --description "Global help for Kronos"
    set_color cyan
    echo "  _  _______   ____  _   _  ____   _____ "
    echo " | |/ /  __ \ / __ \| \ | |/ __ \ / ____|"
    echo " | ' /| |__) | |  | |  \| | |  | | (___  "
    echo " |  < |  _  /| |  | | . ` | |  | |\___ \ "
    echo " | . \| | \ \| |__| | |\  | |__| |____) |"
    echo " |_|\_\_|  \_\____/|_| \_|\____/|_____/ "
    set_color normal
    echo ""
    echo "Active Directory attack orchestrator."
    echo ""
    echo "Kronos is a modular orchestration tool designed to automate and simplify"
    echo "AD penetration testing by wrapping industry-standard tools into a unified CLI."
    echo ""
    set_color yellow
    echo "DEPENDENCIES:"
    set_color normal
    echo "This tool requires several external dependencies to function flawlessly:"
    echo "  - NetExec (nxc), Impacket Scripts, bloodyAD, kerbrute, evil-winrm,"
    echo "    xfreerdp3, bloodhound-python, smbclient, rpcclient, and gum."
    echo ""
    echo "You can install these manually or simply run:"
    set_color green
    echo "  kronos install"
    set_color normal
    echo "to automatically check and install all required utilities."
    echo ""
    echo "USAGE:"
    echo "  kronos <command> [options]"
    echo ""
    echo "COMMANDS:"
    echo "  userenum    Run kerbrute userenum (auto-saves valid_users.txt)"
    echo "  dominfo     Query domain info and password policy"
    echo "  ingest      Ingest AD data using bloodhound-python"
    echo "  connect     Connect via protocols (rdp, winrm, smb, rpc, ftp, mssql)"
    echo "  search      Search and enumerate AD objects (bloodyAD)"
    echo "  asrep-roast Perform AS-REP roasting"
    echo "  kerbroast   Perform Kerberoasting"
    echo "  lookupsid   Enumerate AD SIDs"
    echo "  spray       Password spray using valid_users.txt"
    echo "  forcechange Force change a user's password"
    echo "  gmsa        Read GMSA passwords"
    echo "  add-user    Create a new AD user"
    echo "  add-member  Add a user to an AD group"
    echo "  add-computer Create a new AD computer account"
    echo "  dacl        Manipulate AD object DACLs (Add/Remove ACEs)"
    echo "  secretsdump Dump AD secrets (secretsdump.py)"
    echo "  psexec      Remote command execution (psexec.py)"
    echo "  rbcd        Perform RBCD attack"
    echo "  shadow-credentials Perform Shadow Credentials attack"
    echo "  ticket      Create Golden, Silver, Diamond, and Sapphire Tickets"
    echo "  convert     Convert tickets between kirbi and ccache"
    echo "  request     Request TGT or ST (getTGT/getST)"
    echo "  install     Install all external dependencies"
    echo "  reset       Clear all persistent cache variables"
    echo "  help        Show this global help message"
    echo ""
    echo "Run 'kronos <command> help' for subcommand-specific details."
end