# description: Global help for Kronos
function __kronos_help --description "Global help for Kronos"
    echo "Usage: kronos <command> [options]"
    echo ""
    echo "Active Directory attack orchestrator."
    echo ""
    echo "Commands:"
    echo "  userenum    Run kerbrute userenum (auto-saves valid_users.txt)"
    echo "  dominfo     Query domain info and password policy"
    echo "  ingest      Ingest AD data using bloodhound-python"
    echo "  connect     Connect via protocols (rdp, winrm, smb, rpc, ftp, mssql)"
    echo "  search      Search and enumerate AD objects (bloodyAD)"
    echo "  asrep-roast Perform AS-REP roasting"
    echo "  kerbroast   Perform Kerberoasting"
    echo "  lookupsid   Enumerate AD SIDs"
    echo "  spray       Password spray using valid_users.txt"
    echo "  forcechange Force change a user's password"
    echo "  gmsa        Read GMSA passwords"
    echo "  add-user    Create a new AD user"
    echo "  add-member  Add a user to an AD group"
    echo "  add-computer Create a new AD computer account"
    echo "  dacl        Manipulate AD object DACLs (Add/Remove ACEs)"
    echo "  secretsdump Dump AD secrets (secretsdump.py)"
    echo "  rbcd        Perform RBCD attack"
    echo "  shadow-credentials Perform Shadow Credentials attack"
    echo "  ticket      Create Golden and Silver Tickets"
    echo "  convert     Convert tickets between kirbi and ccache"
    echo "  request     Request TGT or ST (getTGT/getST)"
    echo "  install     Install all external dependencies"
    echo "  help        Show this global help message"
    echo ""
    echo "Run 'kronos <command> help' or 'kronos help <command>' for more info."
end
